# Lowercase keys can be overridden by command line arguments
# Debug mode
debug: false
# Address to bind to
host: 127.0.0.1
# Port to use
port: 5000

# URL to Neo database. Include username and password if required
FEEDER_NEO_URL: http://neo4j:neo4j@localhost:7474/db/data
# Allow login with Google account. If false, only username password can be used.
FEEDER_ALLOW_GOOGLE: true
# If anyone with a Google account is allowed access. If false, then the email
# must be present in the users list below
FEEDER_ALLOW_ANY_GOOGLE: false
# Allow specified users to login with passwords. If false, users can only
# use their google account to login.
FEEDER_ALLOW_USERPASS: true
# You can then specify users and passwords here
FEEDER_USERS:
  # User bob has a very simple password
  bob: secretpassword
  # Alice is smart and stores her password hashed. (Run hashedpassword.py)
  alice: pbkdf2:sha1:1000$1SM0kJhk$99a188f2d1dd95d8a21ac6809911fee5b1c216e4
  # Timmy just uses his google account, but can use the password if configured
  timmy9126@gmail.com: dummypassword
