name: PR Checks

on:
  push:
    branches:
      - '*'
      - '!master'
  # PRs are in gitlab for now
  #pull_request:
  #  branches: [ "master" ]

jobs:
  # this job builds and uploads the apk
  lint_and_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: perform the checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # Verify the SHA-sum
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # This initializes gradle and sets up caching. Default version is the wrapper version.
    - name: gradle build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: classes packageDebugAndroidTest :app:lint check
